name: e_commerce
description: "A Flutter project with Firebase authentication, product listing, and Stripe payments."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¹ Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_functions: ^5.6.2

  # ðŸ”¹ Stripe
  flutter_stripe: ^12.1.1

  # ðŸ”¹ HTTP pour appels API
  http: ^1.1.0

  # ðŸ”¹ Variables d'environnement
  flutter_dotenv: ^6.0.0

  # ðŸ”¹ Pour ouvrir les liens (Stripe Checkout)
  url_launcher: ^6.1.10

  # ðŸ”¹ Pour formater les dates
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/products.json
