name: e_commerce
description: "A new Flutter project."
publish_to: "none" # EmpÃªche la publication accidentelle sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # ðŸ”¹ Firebase core et auth
  firebase_core: ^3.12.0
  firebase_auth: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Exemple pour ajouter des assets si nÃ©cessaire
  # assets:
  #   - assets/images/

  # Exemple pour ajouter des polices personnalisÃ©es
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
